languageCode = "en-us"
baseurl = "https://baas.pw"
title = "ircBaas"
theme = "cocoa-eh"
builddrafts = true
canonifyurls = true
contentdir = "content"
layoutdir = "layouts"
publishdir = "public"
title = "irc Bouncer as a Service"
pluralizelisttitles = false

[permalinks]
blog = "blog/:slug/"

[params]
dateform = "Jan 2, 2006"
dateformfull = "Mon Jan 2 2006 15:04:05 MST"
description = "irc Bouncer as a Service"
logofile = "img/logo.png"
faviconfile = "img/logo.png"
highlightjs = true
lang = "en"
github = "https://github.com/example"
